services:
  - type: web
    name: python-decoder-bot
    env: python
    region: oregon
    plan: free
    
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    
    healthCheckPath: /health
    
    autoDeploy: true
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      
      - key: PORT
        value: 10000
      
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      
      - key: GEMINI_API_KEY
        sync: false
      
      - key: WEBHOOK_URL
        sync: false
